version: '3'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - back

  nest:
    image: zeeeartiste/back-chat-app:latest
    # build: .
    ports:
      - '3000:3000'
    depends_on: ['redis']
    networks:
      - back

networks:
  back:
