version: '3'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - back

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projet
    ports:
      - '5432:5432'
    networks:
      - back

  nest:
    # image: zeeeartiste/back-chat-app:latest
    build: ./backend
    ports:
      - '3000:3000'
    depends_on: 
      - redis
      - postgres
    networks:
      - back

networks:
  back:
