version: "1"

services:
  - type: redis
    name: redis
    plan: free
    ipAllowList: []

  - type: web
    name: nest
    plan: free
    image:
      url: zeeeartiste/back-chat-app:latest
    envVars:
      - key: REDIS_HOST
        value: redis
    runtime: docker
    
