version: '1'

services:
  - type: redis
    name: redis
    plan: free
    ipAllowList: []

  - type: web
    name: nest
    runtime: image
    plan: free
    image:
      url: zeeeartiste/back-chat-app:latest
